### ISSUE TITLE
Suggestion: removing the chmod line to improve container reusability.

### ISSUE THREAD

**Issue by cesarvr** [sclorg/s2i-nodejs-container#167]
Hi ,

This is just a suggestion to delete this line [here](https://github.com/sclorg/s2i-nodejs-container/blob/master/6/Dockerfile#L56), so it can improve container reusability. 

I understand the point for that line from security point of view, and last year I saw the same line in some mainstream containers but I think this kill container reusability. 

What do I mean by reusability, take a look at this example: 

- I want to create an image using Openshift 3 s2i-nodejs-container to create an immutable image.
- Now I would like to take advantage of the fact that is immutable, so I want to check that my service is fine by running the unit test, for this I create a  [kube/job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) and I expect back an XML with the result of my test so I can stream it to Jenkins. 

```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: utest 
spec:
  template:
    metadata:
      name: utest
    spec:
      containers:
      - name: node-unit-test
        image: 172.30.1.1:5000/my-project/service:latest 
        command: ["npm", 'test', '-S']
      restartPolicy: OnFailure
  backoffLimit: 2
  acriveDeadlineSeconds: 50
```
- With the current image I get this back: 

```sh
Containers:
  node-unit-test:
    Container ID:	docker://c17f268e6d3c304dc7b816c9118ca89d3e1ba006f197c701d5e344c2ea25326d
    Image:		172.30.1.1:5000/openshift/nodejs:latest
    Image ID:		docker-pullable://172.30.1.1:5000/openshift/nodejs@sha256:7d1492696c052ca5b671efaebfe967c71f4248e74b92a347410928cc1e5bb578
    Port:		<none>
    Command:
      npm
      test
     -S
    State:	Waiting
      Reason:	RunContainerError
    Last State:	Terminated
      Reason:	ContainerCannotRun
      Message:	oci runtime error: container_linux.go:265: starting container process caused "exec: \"npm\": executable file not found in $PATH"
```

I think the reason for this is because of the dropping the user privileges in the build step, can this line being deleted ? 

 **Successful example** 

Example using mainstream [Nodejs](https://hub.docker.com/_/node/) images: 

- Pulling from library/node:4.8
   `oc import-image node4 --from=registry.hub.docker.com/library/node:4.8 --confirm`

- Creating job
```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: utest 
spec:
  template:
    metadata:
      name: utest
    spec:
      containers:
      - name: node-unit-test
        image: 172.30.1.1:5000/my-project/node4   # imagestream node4
        command: ["npm", 'test', '-S']
      restartPolicy: OnFailure
  backoffLimit: 2
  acriveDeadlineSeconds: 50
```

- Executing

```
oc logs utest-65slz

<testsuite name="Mocha Tests" tests="2" failures="0" errors="0" skipped="0" timestamp="Wed, 15 Nov 2017 14:47:13 GMT" time="0.008">
  <testcase classname="Testing DB Functions" name="Config object construction" time="0.003"/>
  <testcase classname="Testing DB Functions" name="Config.getRaw should load config file" time="0.002"/>
</testsuite>
```

Thanks.

**Comment by pkubatrh** [comment]
The command needs to be wrapped into a bash call:

```
$ docker exec -ti a498f4ae70cf bash -c "npm test -S"
npm ERR! path /opt/app-root/src/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/opt/app-root/src/package.json'
```

Without that the nodejs scl will not be enabled and thus npm is not found in PATH:

```
$ docker exec -ti a498f4ae70cf npm test -S
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"npm\": executable file not found in $PATH"
```

**Comment by cesarvr** [comment]
Hi, 

I try your suggestion with this result: 

<img width="1211" alt="screen shot 2017-11-16 at 11 10 50" src="https://user-images.githubusercontent.com/3899337/32888389-068863a4-cabf-11e7-9466-8af622ad493d.png">

Still can't find anything inside the container. 

here is the job template I'm using: 

```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: utest
spec:
  template:
    metadata:
      name: utest
    spec:
      containers:
      - name: node-unit-test
        image: 172.30.1.1:5000/openshift/nodejs:6
        command: ['bash -c'," \"node -v\"  "]
      restartPolicy: OnFailure
  backoffLimit: 2
  acriveDeadlineSeconds: 50

```

**Comment by pkubatrh** [comment]
This works for me:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: utest
spec:
  template:
    metadata:
      name: utest
    spec:
      containers:
      - name: node-unit-test
        image: 172.30.1.1:5000/openshift/nodejs:6
        command: ["bash", "-c", "node -v"]
      restartPolicy: OnFailure
  backoffLimit: 2
  acriveDeadlineSeconds: 50
```

```
$ oc logs utest-xftc2
v6.9.1
```
